#HATS Collection
obs_collection=catalog
hats_primary_table_url=catalog
all_margins=catalog_5arcs
default_margin=catalog_5arcs
hats_builder=lsdb v0.9.0, hats v0.9.0
hats_creation_date=2026-07-20T18:52UTC
hats_estsize=2299
hats_release_date=2025-08-22
hats_version=v1.0
